version: '3'
services:
  scis-redis:
    image: redis:6-alpine3.12
    container_name: scis-redis
    ports:
      - 6378:6379
  scis-mysql:
    image: mysql:8.0.21
    container_name: scis-mysql
    command:
      -- mysqld --character-set-server=utf8mb4
    volumes:
      - /scis/mysql/data/db:/var/lib/mysql
      - /scis/mysql/conf:/etc/mysql/conf.d
      - /scis/mysql/log:/var/log/mysql
    ports:
      - 3305:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  scis-minio:
    image: minio/minio:RELEASE.2021-01-05T05-22-38Z
    container_name: scis-minio
    ports:
      - 9002:9000
    environment:
      MINIO_ACCESS_KEY: root
      MINIO_SECRET_KEY: 12345678
    volumes:
      - /scis/minio/data:/data
      - /scis/minio/config:/root/.minio
    command:
      server /data

