name: Node.js Vue.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
        working-directory: ./web
      - run: npm run build --if-present
        working-directory: ./web
      - run: npm test
        working-directory: ./web
        env:
          CI: true
