name: Node.js Vue.js CI

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
        working-directory: ./web
      - name: npm build
      - run: npm run build
        working-directory: ./web
      - name: npm test
      - run: npm test
        working-directory: ./web
      - uses: actions/upload-artifact@v2
      - name: up artifact
        with:
          name: Package dist
          path: |
            dist
            !dist/**/*.md
          retention-days: 30
        env:
          CI: true

