name: Node.js Vue.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['8.x', '10.x', '12.x']

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
        working-directory: ./web
      - run: npm run build --if-present
        working-directory: ./web
      - run: npm test
        working-directory: ./web
        env:
          CI: true
