name: Node.js Vue.js CI

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: |
          npm install
          npm run build
          npm test
        working-directory: ./web
        env:
          CI: true
      - name: up artifact
        uses: actions/upload-artifact@v2
        with:
          name: Package dist
          path: web/dist
          retention-days: 30

